# Generated by Django 4.2.6 on 2023-10-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('moderator', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestServices',
            fields=[
                ('id_request_services', models.AutoField(primary_key=True, serialize=False)),
                ('id_request', models.ForeignKey(blank=True, db_column='id_request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_assist.requests')),
                ('id_service', models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_assist.services')),
            ],
            options={
                'db_table': 'request_services',
                'managed': True,
            },
        ),
    ]
