# Generated by Django 4.2.6 on 2023-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0002_services_location_services_support_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
