# Generated by Django 4.2.6 on 2023-10-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0003_alter_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='location',
            new_name='location_service',
        ),
    ]
