# Generated by Django 4.2.6 on 2023-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0005_services_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='moderator',
        ),
        migrations.AddField(
            model_name='users',
            name='is_moderator',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
