# Generated by Django 4.2.6 on 2023-10-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0006_remove_requests_moderator_users_is_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
