# Generated by Django 4.2.6 on 2023-10-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0007_rename_creator_requests_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='creator_id',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_assist.users'),
        ),
    ]
