# Generated by Django 4.2.6 on 2023-10-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0010_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='formation_date',
        ),
    ]
