# Generated by Django 4.2.6 on 2023-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_assist', '0011_remove_requests_formation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
