# Generated by Django 4.2.6 on 2023-10-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('moderating', 'Проверяется'), ('approved', 'Принято'), ('denied', 'Отказано'), ('deleted', 'Удалено')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(blank=True, choices=[('operating', 'действует'), ('deleted', 'удален')], max_length=20, null=True),
        ),
    ]
