# Generated by Django 4.2.6 on 2023-12-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_service',
            new_name='id_user',
        ),
    ]
