# Generated by Django 4.2.6 on 2024-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_id_service_customuser_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='service_provided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
