# Generated by Django 4.2.6 on 2023-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_requests_status_alter_services_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='been_moderated',
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'зарегистрирован'), ('moderating', 'на рассмотрении'), ('approved', 'принят'), ('denied', 'отказано'), ('deleted', 'удален')], max_length=20, null=True),
        ),
    ]
