# Generated by Django 4.2.6 on 2024-01-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_requests_service_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='service_provided',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
