# Generated by Django 4.2.6 on 2024-01-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_requests_service_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
