# Generated by Django 4.2.6 on 2023-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'зарегистрирован'), ('moderating', 'на рассмотрении'), ('approved', 'принято'), ('denied', 'отказано'), ('deleted', 'удален')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
