# Generated by Django 4.2.6 on 2024-01-15 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_requests_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='requests',
            name='moderator_id',
            field=models.ForeignKey(blank=True, db_column='moderator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Является ли пользователь модератором?'),
        ),
    ]
